version: '3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.18.0
    container_name: turbotools-uptime-kuma
    restart: unless-stopped
    volumes:
      - uptime-kuma_data:/app/data
    ports:
      - 3001:3001

volumes:
  uptime-kuma_data: